### ISSUE TITLE
Underwear Patrols

### ISSUE THREAD

**Issue by briankgregory** [dayzai/A3EAI#11] opened 2015-08-21 23:36 UTC
Since updating to 0.8.4 and EPOCH 0.3.2 with all the dynamic lists enabled all AI appear without backpacks or uniforms.

**Comment by briankgregory** [comment] 2015-08-21 23:59
Setting all the dynamic lists to false seems to have no change.

**Comment by dayzai** [comment] 2015-08-22 01:34
Redownload the latest version of A3EAI. The recent versions had a hiccup with the loadout generation but should now be fixed in 0.8.4d.

**Comment by briankgregory** [comment] 2015-08-22 01:35
Got ya, thanks for the fast response.

**Comment by northrivergeek** [comment] 2015-10-01 20:40
I still see ai in underware often.. even in the new version

**Comment by dayzai** [comment] 2015-10-02 00:47
Not a bug. The A3EAI_addUniformChance0-3 settings control the probability of adding a uniform item.

**Closed by dayzai** 2015-10-02 00:47 UTC
